cursos_homepage:
  path: /
  defaults: { _controller: CursosBundle:Sistema:index }

login:
  path: /login
  defaults: { _controller: CursosBundle:Usuario:login }

login_check:
  path: /login_check

logout:
  path: /logout

persona_index:
  path: /persona/perfil/{id}
  defaults: { _controller: CursosBundle:Persona:index }

persona_report:
  path: /persona/report
  defaults: { _controller: CursosBundle:Persona:report }

persona_excel_report:
  path: /persona/excel_report
  defaults: { _controller: CursosBundle:Persona:excelReport }

persona_pdf_report:
  path: /persona/pdf_report
  defaults: { _controller: CursosBundle:Persona:pdfReport }

persona_register:
  path: /persona/register
  defaults: { _controller: CursosBundle:Persona:register }

persona_edit:
  path: /persona/edit/{id}
  defaults: { _controller: CursosBundle:Persona:edit }

persona_delete:
  path: /persona/delete/{id}
  defaults: { _controller: CursosBundle:Persona:delete }

usuario_register:
  path: /usuario/register
  defaults: { _controller: CursosBundle:Usuario:register }

telefono_register:
  path: /telefono/register
  defaults: { _controller: CursosBundle:Telefono:register }

curso_index:
  path: /curso
  defaults: { _controller: CursosBundle:Curso:index }

curso_register:
  path: /curso/register
  defaults: { _controller: CursosBundle:Curso:register }

curso_suscribe:
  path: /curso/suscribe/{id}
  defaults: { _controller: CursosBundle:Curso:suscribe }

curso_unsuscribe:
  path: /curso/unsuscribe/{id}
  defaults: { _controller: CursosBundle:Curso:unsuscribe }

curso_edit:
  path: /curso/edit/{id}
  defaults: { _controller: CursosBundle:Curso:edit }

curso_delete:
  path: /curso/delete/{id}
  defaults: { _controller: CursosBundle:Curso:delete }